blog/urls.py
from django.urls import path
from . import views

app_name = 'blog' # set namespace

urlpatterns = [
  path('', views.post_list, name='post_list'),
  path('create_post', views.create_post, name='create_post')
]

mysite/urls.py
from django.urls import path, include
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]

blog/models.py
from django.utils import timezone
from django.db import models
from django.conf import settings 

class Post(models.Model):
  author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
  title = models.CharField(max_length=200)
  text = models.TextField()
  created_date = models.DateTimeField(default=timezone.now)
  published_date = models.DateTimeField(blank=True, null=True)

  def publish(self):
    self.published_date = timezone.now()
    self.save()

  def __str__(self):
    return self.title

blog/views.py
from django.shortcuts import render, redirect

from blog.models import Post
from django.contrib.auth.models import User

def post_list(request):
  posts = Post.objects.all()

  return render(request, 'blog/post_list.html', {
    'title': 'hello world',
    'posts': posts,
  })

def create_post(request):
  if request.method == 'GET':
    return render(request, 'blog/create_post.html', {})
  
  elif request.method == 'POST':
    author = request.POST['author']
    title = request.POST['title']
    text = request.POST['text']

    me = User.objects.get(username='admin')
    Post.objects.create(author=me, title=title, text=text)

    return redirect('blog:post_list')
    

blog/templates/blog/create_post.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>CREATE Post</title>
</head>
<body>
  <form method="post">
    {% csrf_token %}
    <div>
      <label for="author">author</label>
      <input id="author" name="author"/>
    </div>
    <div>
      <label for="title">title</label>
      <input id="title" name="title"/>
    </div>
    <div>
      <label for="text">text</label>
      <textarea id="text" name="text"></textarea>
    </div>
    <button type="submit">등록하기</button>
  </form>
</body>
</html>

blog/templates/blog/post_list.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>BLOG Page</title>
</head>
<body>
  <h1>BLOG Page</h1>

  <p>{{ title }}</p>

  <ol>
    {% for post in posts %}
      <li>
        <div>
          {{ post.title }}
        </div>
        <div>
          {{ post.author.username }}
        </div>
        <div>
          {{ post.text }}
        </div>
        <hr />
      </li>
    {% endfor %}
  </ol>
  <a href="{% url 'blog:create_post' %}">등록하기</a>
</body>
</html>